### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by zdhickman** [golf1052/SeattleCarsInBikeLanes#3]
<img width="681" alt="Screenshot 2022-11-13 at 1 55 42 AM" src="https://user-images.githubusercontent.com/2453653/201509798-3c9296b8-e5c7-4b38-b8ea-d9da6300240c.png">

**Comment by golf1052** [comment]
I added a description tag in eba3e4d9b6608b7e66fa9c9d8d4e17cc89c8c3bf
```html
<meta name="description" content="Pictures of cars in bike lanes. Accepting submissions through website, Twitter/Mastodon mention, or DM.">
```

Let me know if I should add others.
