### ISSUE TITLE
Sign in with Mastodon isn't working

### ISSUE THREAD

**Issue by tsibley** [golf1052/SeattleCarsInBikeLanes#4]
The server returns an HTTP 500 when the client makes a request for the OAuth2 URL, reproducible with curl:

```
$ curl -siL https://seattle.carinbikelane.com/api/Mastodon/GetOAuthUrl --data-raw '{"serverUrl":"https://metasocial.com"}' --header 'Content-Type: application/json; charset=utf-8'
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Date: Thu, 15 Dec 2022 19:32:02 GMT
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=…d53;Path=/;HttpOnly;Secure;Domain=seattle.carinbikelane.com
Set-Cookie: ARRAffinitySameSite=…d53;Path=/;HttpOnly;SameSite=None;Secure;Domain=seattle.carinbikelane.com
X-Powered-By: ASP.NET
```

**Comment by golf1052** [comment]
Trying locally right now but https://metasocial.com seems to be down right now. Once it's back up I'll be able to investigate further.

**Comment by tsibley** [comment]
Hmm, it's up for me right now. Is it still down for you? (In general I haven't noticed blips with it.)

**Comment by golf1052** [comment]
I've gotten it fixed now. Key Vault permissions weren't set correctly for the App Service. Please re-open if you run into issues.
