### ISSUE TITLE
Suggestion: add Tweet text in the data

### ISSUE THREAD

**Issue by ChessPiece21** [golf1052/SeattleCarsInBikeLanes#6]
This dataset is **AWESOME,** but I think it could be even more accessible and reusable for a variety of users if text from the original tweets were included in the data in some way, even if it's just in the dataset and not in the website. This is a minor suggestion but I think it could help with data analysis of the subject in a more sophisticated way, like subject analysis or topic modeling.

**Comment by golf1052** [comment]
By text from the original tweets I assume you mean the text from the tweet/post that is being quoted? While it is an interesting idea

1. I'd estimate at least half of the original tweets just mention the account or include the street name while the other half actually have details about the picture.
2. This idea falls outside the current scope of the project.

I'm not opposed however to making it easier for someone who's interested in collecting the text from the original tweet by adding a new field in the CSV output but the twitter link is already exported and I know that can be used to get the quote tweet. See [the get tweets id API](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) using `expansions=referenced_tweets.id` and `tweet.fields=referenced_tweets`
